---
title: "Webscraping"
author: "Nicholas Paschall"
date: '2023-03-13'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
library(tm)
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2022")


x <- scan("2022 NFL Combine Results _ Pro-Football-Reference.com.html", 
          what="character", sep="\n")

for(i in length(x) ){ 
    z <- x[ which( "<tr data-row" == str_extract(x, "(<tr data-row)", group=1) ) ] 
}

df <- data.frame( player = rep("", length(z) ) )
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2 )
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1 )
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1 )
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1 )
    df$Wt[i] = as.numeric( str_extract( z[i], "weight\\\">([^<]+)", group=1 ) )
    df$forty_yd[i] = as.numeric( str_extract( z[i], "forty_yd\\\">([^<]+)", group=1 ) )
    df$vertical[i] = as.numeric( str_extract( z[i], "vertical\\\">([^<]+)", group=1 ) )
    df$bench[i] = as.numeric( str_extract( z[i], "bench_reps\\\">([^<]+)", group=1 ) )
    df$broad_jump[i] = as.numeric( str_extract( z[i], "broad_jump\\\">([^<]+)", group=1 ) )
    df$cone[i] = as.numeric( str_extract( z[i], "cone\\\">([^<]+)", group=1 ) )
    df$shuttle[i] = as.numeric( str_extract( z[i], "shuttle\\\">([^<]+)", group=1 ) )
    df$draft.round[i] = as.numeric( str_extract( z[i], "s / ([^t|r|s|n])", group=1 ) ) 
    df$draft.pick[i] = as.numeric( str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1 ) )
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1 )
}

df.2022 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2022$pos.fac <- NA 
for( i in seq_along(df.2022$pos)){
    if(df.2022$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2022$pos.fac[i] = "skill"
    }
    else if(df.2022$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2022$pos.fac[i] = "big skill"
    }
    else if(df.2022$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2022$pos.fac[i] = "combo"
    }
}

df.2022$.html <- NA
for(i in 1:nrow(df.2022)){
    df.2022$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}

for( i in 1:nrow(df.2022)){
    print(paste(df.2022$player[i], df.2022$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2022$.html[i])){
        print(i)
        x <- scan(df.2022$.html[i], what="character", sep="\n", skip=600, nlines=400)
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2022$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2022$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2022$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2022$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2022$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2022$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2022$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2022$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2022$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2022$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2022$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2022$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2022$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2022$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2022$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2022$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2022$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2022$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2022$pos[i] %in% c("QB")){
            df.2022$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2022$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2022$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2022$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2022$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2022$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2022$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2022$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2022$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2022 <- df.2022 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) %>%
    filter(!is.na(.html))

#manual inputs:
draft_2022$rec[118] <- 120 ; draft_2022$rec_yds[118] <- 1434 ; draft_2022$rec_avg[118] <- 12.0 ; draft_2022$rec_td[118] <- 11
draft_2022$rec[237] <- 118 ; draft_2022$rec_yds[237] <- 1648 ; draft_2022$rec_avg[237] <- 14.0 ; draft_2022$rec_td[237] <- 12

#write.csv(draft_2022, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2022.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2021")
x <- scan("2021 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2021 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2021$pos.fac <- NA 
for( i in seq_along(df.2021$pos)){
    if(df.2021$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2021$pos.fac[i] = "skill"
    }
    else if(df.2021$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2021$pos.fac[i] = "big skill"
    }
    else if(df.2021$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2021$pos.fac[i] = "combo"
    }
}

df.2021$.html <- NA
for(i in 1:nrow(df.2021)){
    df.2021$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}

for( i in 1:nrow(df.2021)){
    print(paste(df.2021$player[i], df.2021$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2021$.html[i])){
        print(i)
        x <- scan(df.2021$.html[i], what="character", sep="\n", skip=600, nlines=400)
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2021$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2021$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2021$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2021$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2021$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2021$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2021$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2021$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2021$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2021$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2021$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2021$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2021$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2021$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2021$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2021$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2021$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2021$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2021$pos[i] %in% c("QB")){
            df.2021$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2021$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2021$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2021$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2021$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2021$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2021$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2021$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2021$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2021 <- df.2021 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) %>%
    filter(!is.na(.html))

#manual inputs:


write.csv(draft_2021, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2021.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2020")
x <- scan("2020 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2020 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2020$pos.fac <- NA 
for( i in seq_along(df.2020$pos)){
    if(df.2020$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2020$pos.fac[i] = "skill"
    }
    else if(df.2020$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2020$pos.fac[i] = "big skill"
    }
    else if(df.2020$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2020$pos.fac[i] = "combo"
    }
}

df.2020$.html <- NA
for(i in 1:nrow(df.2020)){
    df.2020$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}

for( i in 1:nrow(df.2020)){
    print(paste(df.2020$player[i], df.2020$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2020$.html[i])){
        print(i)
        x <- scan(df.2020$.html[i], what="character", sep="\n", skip=600, nlines=400)
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2020$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2020$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2020$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2020$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2020$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2020$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2020$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2020$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2020$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2020$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2020$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2020$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2020$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2020$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2020$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2020$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2020$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2020$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2020$pos[i] %in% c("QB")){
            df.2020$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2020$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2020$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2020$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2020$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2020$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2020$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2020$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2020$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2020 <- df.2020 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) %>%
    filter(!is.na(.html))

#manual inputs:

write.csv(draft_2020, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2020.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2019")
x <- scan("2019 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2019 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2019$pos.fac <- NA 
for( i in seq_along(df.2019$pos)){
    if(df.2019$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2019$pos.fac[i] = "skill"
    }
    else if(df.2019$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2019$pos.fac[i] = "big skill"
    }
    else if(df.2019$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2019$pos.fac[i] = "combo"
    }
}

df.2019$.html <- NA
for(i in 1:nrow(df.2019)){
    df.2019$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}

df.2019$.html[66] <- NA # Byron Cowart
df.2019$.html[213] <- NA #Jakobi Meyers
df.2019$.html[295] <- NA # Derrek Thomas

for( i in 295:nrow(df.2019)){
    print(paste(df.2019$player[i], df.2019$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2019$.html[i])){
        print(i)
        x <- scan(df.2019$.html[i], what="character", sep="\n", skip=600, nlines=400)
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2019$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2019$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2019$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2019$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2019$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2019$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2019$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2019$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2019$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2019$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2019$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2019$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2019$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2019$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2019$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2019$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2019$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2019$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2019$pos[i] %in% c("QB")){
            df.2019$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2019$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2019$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2019$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2019$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2019$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2019$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2019$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2019$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2019 <- df.2019 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) %>%
    filter(!is.na(.html))

#manual inputs:
draft_2019$rush_att[241] <- 257 ; draft_2019$rush_yds[241] <- 1636 ; draft_2019$rush_avg[241] <- 6.4 ; draft_2019$rush_td[241] <- 20

write.csv(draft_2019, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2019.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2018")
x <- scan("2018 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2018 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2018$pos.fac <- NA 
for( i in seq_along(df.2018$pos)){
    if(df.2018$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2018$pos.fac[i] = "skill"
    }
    else if(df.2018$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2018$pos.fac[i] = "big skill"
    }
    else if(df.2018$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2018$pos.fac[i] = "combo"
    }
}

df.2018$.html <- NA
for(i in 1:nrow(df.2018)){
    df.2018$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}

df.2018$.html[99] <- NA #Dimitri Flowers

for( i in 173:nrow(df.2018)){
    print(paste(df.2018$player[i], df.2018$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2018$.html[i])){
        print(i)
        x <- scan(df.2018$.html[i], what="character", sep="\n", skip=600, nlines=400)
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2018$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2018$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2018$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2018$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2018$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2018$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2018$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2018$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2018$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2018$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2018$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2018$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2018$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2018$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2018$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2018$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2018$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2018$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2018$pos[i] %in% c("QB")){
            df.2018$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2018$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2018$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2018$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2018$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2018$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2018$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2018$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2018$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}


#manual inputs:
draft_2018$tackles_solo[4] <- 68 ; draft_2018$tackles_ast[4] <- 50 ; draft_2018$tackles_tot[4] <- 118 ; draft_2018$tackles_loss[4] <- 28.0 ; draft_2018$sacks[4] <- 12.5 ; draft_2018$def_int[4] <- 0 ; draft_2018$forced_fumble[4] <- 3 ; draft_2018$pass_defended[4] <- 2

draft_2018$tackles_solo[12] <- 89 ; draft_2018$tackles_ast[12] <- 53 ; draft_2018$tackles_tot[12] <- 142 ; draft_2018$tackles_loss[12] <- 34.5 ; draft_2018$sacks[12] <- 15.5 ; draft_2018$def_int[12] <- 0 ; draft_2018$forced_fumble[12] <- 6 ; draft_2018$pass_defended[12] <- 8

draft_2018$rec[69] <- 45 ; draft_2018$rec_yds[69] <- 528 ; draft_2018$rec_avg[69] <- 11.7 ; draft_2018$rec_td[69] <- 5

draft_2018$tackles_solo[76] <- 103 ; draft_2018$tackles_ast[76] <- 67 ; draft_2018$tackles_tot[76] <- 170 ; draft_2018$tackles_loss[76] <- 21.0 ; draft_2018$sacks[76] <- 14 ; draft_2018$def_int[76] <- 0 ; draft_2018$forced_fumble[76] <- 4 ; draft_2018$pass_defended[76] <- 0

draft_2018$rec[81] <- 54 ; draft_2018$rec_yds[81] <- 886 ; draft_2018$rec_avg[81] <- 16.4 ; draft_2018$rec_td[81] <- 13 ; draft_2018$rush_att[81] <- 36 ; draft_2018$rush_yds[81] <- 151 ; draft_2018$rush_avg[81] <- 4.2 ; draft_2018$rush_td[81] <- 4

draft_2018$tackles_solo[100] <- 30 ; draft_2018$tackles_ast[100] <- 41 ; draft_2018$tackles_tot[100] <- 71 ; draft_2018$tackles_loss[100] <- 14.5 ; draft_2018$sacks[100] <- 9 ; draft_2018$def_int[100] <- 0 ; draft_2018$forced_fumble[100] <- 1 ; draft_2018$pass_defended[100] <- 1

draft_2018$tackles_solo[101] <- 116 ; draft_2018$tackles_ast[101] <- 49 ; draft_2018$tackles_tot[101] <- 165 ; draft_2018$tackles_loss[101] <- 7.5 ; draft_2018$sacks[101] <- 0 ; draft_2018$def_int[101] <- 5 ; draft_2018$forced_fumble[101] <- 0 ; draft_2018$pass_defended[101] <- 21

draft_2018$rec[108] <- 86 ; draft_2018$rec_yds[108] <- 1048 ; draft_2018$rec_avg[108] <- 12.2 ; draft_2018$rec_td[108] <- 7

draft_2018$tackles_solo[118] <- 67 ; draft_2018$tackles_ast[118] <- 63 ; draft_2018$tackles_tot[118] <- 130 ; draft_2018$tackles_loss[118] <- 32 ; draft_2018$sacks[118] <- 13.5 ; draft_2018$def_int[118] <- 0 ; draft_2018$forced_fumble[118] <- 2 ; draft_2018$pass_defended[118] <- 3

draft_2018$rec[120] <- 182 ; draft_2018$rec_yds[120] <- 2899 ; draft_2018$rec_avg[120] <- 15.9 ; draft_2018$rec_td[120] <- 21

draft_2018$tackles_solo[121] <- 105 ; draft_2018$tackles_ast[121] <- 96 ; draft_2018$tackles_tot[121] <- 201 ; draft_2018$tackles_loss[121] <- 22.5 ; draft_2018$sacks[121] <- 6.5 ; draft_2018$def_int[121] <- 0 ; draft_2018$forced_fumble[121] <- 4 ; draft_2018$pass_defended[121] <- 4

draft_2018$rec[123] <- 44 ; draft_2018$rec_yds[123] <- 375 ; draft_2018$rec_avg[123] <- 8.5 ; draft_2018$rec_td[123] <- 4 ; draft_2018$rush_att[123] <- 321 ; draft_2018$rush_yds[123] <- 1596 ; draft_2018$rush_avg[123] <- 5.0 ; draft_2018$rush_td[123] <- 17

draft_2018$rec[132] <- 243 ; draft_2018$rec_yds[132] <- 3249 ; draft_2018$rec_avg[132] <- 13.4 ; draft_2018$rec_td[132] <- 23 ; draft_2018$rush_att[132] <- 61 ; draft_2018$rush_yds[132] <- 554 ; draft_2018$rush_avg[132] <- 9.1 ; draft_2018$rush_td[132] <- 5

draft_2018$rec[162] <- 150 ; draft_2018$rec_yds[162] <- 1683 ; draft_2018$rec_avg[162] <- 11.2 ; draft_2018$rec_td[162] <- 17

draft_2018$tackles_solo[168] <- 51 ; draft_2018$tackles_ast[168] <- 52 ; draft_2018$tackles_tot[168] <- 103 ; draft_2018$tackles_loss[168] <- 23 ; draft_2018$sacks[168] <- 5.5 ; draft_2018$def_int[168] <- 0 ; draft_2018$forced_fumble[168] <- 1 ; draft_2018$pass_defended[168] <- 9

draft_2018$tackles_solo[169] <- 14 ; draft_2018$tackles_ast[169] <- 22 ; draft_2018$tackles_tot[169] <- 36 ; draft_2018$tackles_loss[169] <- 1.5 ; draft_2018$sacks[169] <- 1 ; draft_2018$def_int[169] <- 0 ; draft_2018$forced_fumble[169] <- 1 ; draft_2018$pass_defended[169] <- 1

draft_2018$rec[174] <- 158 ; draft_2018$rec_yds[174] <- 2477 ; draft_2018$rec_avg[174] <- 15.7 ; draft_2018$rec_td[174] <- 21

draft_2018$tackles_solo[198] <- 82 ; draft_2018$tackles_ast[198] <- 61 ; draft_2018$tackles_tot[198] <- 143 ; draft_2018$tackles_loss[198] <- 2.5 ; draft_2018$sacks[198] <- 1 ; draft_2018$def_int[198] <- 2 ; draft_2018$forced_fumble[198] <- 0 ; draft_2018$pass_defended[198] <- 3

draft_2018$rec[201] <- 69 ; draft_2018$rec_yds[201] <- 662 ; draft_2018$rec_avg[201] <- 9.6 ; draft_2018$rec_td[201] <- 7 ; draft_2018$rush_att[201] <- 647 ; draft_2018$rush_yds[201] <- 3202 ; draft_2018$rush_avg[201] <- 4.9 ; draft_2018$rush_td[201] <- 26

draft_2018$tackles_solo[205] <- 98 ; draft_2018$tackles_ast[205] <- 81 ; draft_2018$tackles_tot[205] <- 179 ; draft_2018$tackles_loss[205] <- 63 ; draft_2018$sacks[205] <- 42 ; draft_2018$def_int[205] <- 2 ; draft_2018$forced_fumble[205] <- 10 ; draft_2018$pass_defended[205] <- 3

draft_2018$tackles_solo[207] <- 58 ; draft_2018$tackles_ast[207] <- 80 ; draft_2018$tackles_tot[207] <- 138 ; draft_2018$tackles_loss[207] <- 25 ; draft_2018$sacks[207] <- 19 ; draft_2018$def_int[207] <- 0 ; draft_2018$forced_fumble[207] <- 2 ; draft_2018$pass_defended[207] <- 2

draft_2018$rec[220] <- 168 ; draft_2018$rec_yds[220] <- 2748 ; draft_2018$rec_avg[220] <- 16.4 ; draft_2018$rec_td[220] <- 22

draft_2018$rec[239] <- 18 ; draft_2018$rec_yds[239] <- 230 ; draft_2018$rec_avg[239] <- 12.8 ; draft_2018$rec_td[201] <- 1 ; draft_2018$rush_att[239] <- 86 ; draft_2018$rush_yds[239] <- 475 ; draft_2018$rush_avg[239] <- 5.5 ; draft_2018$rush_td[239] <- 3

draft_2018$tackles_solo[241] <- 118 ; draft_2018$tackles_ast[241] <- 43 ; draft_2018$tackles_tot[241] <- 161 ; draft_2018$tackles_loss[241] <- 7 ; draft_2018$sacks[241] <- 1 ; draft_2018$def_int[241] <- 7 ; draft_2018$forced_fumble[241] <- 0 ; draft_2018$pass_defended[241] <- 21

draft_2018$tackles_solo[242] <- 49 ; draft_2018$tackles_ast[242] <- 33 ; draft_2018$tackles_tot[242] <- 82 ; draft_2018$tackles_loss[242] <- 3 ; draft_2018$sacks[242] <- 1 ; draft_2018$def_int[242] <- 2 ; draft_2018$forced_fumble[242] <- 1 ; draft_2018$pass_defended[242] <- 16

draft_2018$rec[253] <- 23 ; draft_2018$rec_yds[253] <- 242 ; draft_2018$rec_avg[253] <- 10.5 ; draft_2018$rec_td[253] <- 2 ; draft_2018$rush_att[253] <- 204 ; draft_2018$rush_yds[253] <- 1150 ; draft_2018$rush_avg[253] <- 5.6 ; draft_2018$rush_td[253] <- 13

draft_2018$rec[259] <- 124 ; draft_2018$rec_yds[259] <- 1862 ; draft_2018$rec_avg[259] <- 15.0 ; draft_2018$rec_td[259] <- 17

draft_2018$pass_cmp[261] <- 863 ; draft_2018$pass_att[261] <- 1393 ; draft_2018$pass_pct[261] <- 62 ; draft_2018$pass_yds[261] <- 11262 ; draft_2018$pass_yds_att[261] <- 8.1 ; draft_2018$adj_pass_yds_att[261] <- 8.1 ; draft_2018$pass_td[261] <- 74 ; draft_2018$pass_int[261] <- 31 ; draft_2018$pass_rating[261] <- 142.9

draft_2018$rec[269] <- 70 ; draft_2018$rec_yds[269] <- 527 ; draft_2018$rec_avg[269] <- 7.5 ; draft_2018$rec_td[269] <- 2 ; draft_2018$rush_att[269] <- 561 ; draft_2018$rush_yds[269] <- 3204 ; draft_2018$rush_avg[269] <- 5.7 ; draft_2018$rush_td[269] <- 32

draft_2018 <- df.2018 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT"))
#write.csv(draft_2018, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2018.csv")
```

```{r}

setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2017")
x <- scan("2017 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2017 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2017$pos.fac <- NA 
for( i in seq_along(df.2017$pos)){
    if(df.2017$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2017$pos.fac[i] = "skill"
    }
    else if(df.2017$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2017$pos.fac[i] = "big skill"
    }
    else if(df.2017$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2017$pos.fac[i] = "combo"
    }
}

df.2017$.html <- NA
for(i in 1:nrow(df.2017)){
    df.2017$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2017$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2017$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2017$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2017)){
    print(paste(df.2017$player[i], df.2017$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2017$.html[i])){
        print(i)
        x <- try(scan(df.2017$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2017$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2017$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2017$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2017$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2017$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2017$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2017$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2017$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2017$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2017$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2017$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2017$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2017$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2017$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2017$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2017$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2017$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2017$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2017$pos[i] %in% c("QB")){
            df.2017$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2017$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2017$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2017$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2017$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2017$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2017$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2017$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2017$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2017 <- df.2017 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

draft_2017$rush_att[107] <- 591 ; draft_2017$rush_yds[107] <- 2651 ; draft_2017$rush_avg[107] <- 4.5 ; draft_2017$rush_td[107] <- 24 ; draft_2017$rec[107] <- 58 ; draft_2017$rec_yds[107] <- 444 ; draft_2017$rec_avg[107] <- 7.7; draft_2017$rec_td[107] <- 0

draft_2017$tackles_solo[115] <- 34 ; draft_2017$tackles_ast[115] <- 36 ; draft_2017$tackles_tot[115] <- 70 ; draft_2017$tackles_loss[115] <- 8.5 ; draft_2017$sacks[115] <- 6.0; draft_2017$def_int[115] <- 1 ; draft_2017$forced_fumble[115] <- 1

draft_2017$rec[120] <- 399 ; draft_2017$rec_yds[120] <- 4279 ; draft_2017$rec_avg[120] <- 10.7; draft_2017$rec_td[120] <- 23

draft_2017$rec[124] <- 25 ; draft_2017$rec_yds[124] <- 228 ; draft_2017$rec_avg[124] <- 9.1; draft_2017$rec_td[124] <- 2 ; draft_2017$rush_att[124] <- 557 ; draft_2017$rush_yds[124] <- 2381 ; draft_2017$rush_avg[124] <- 4.3 ; draft_2017$rush_td[124] <- 39

write.csv(draft_2017, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2017.csv")
```

```{r}

setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2013")
x <- scan("2013 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2013 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2013$pos.fac <- NA 
for( i in seq_along(df.2013$pos)){
    if(df.2013$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2013$pos.fac[i] = "skill"
    }
    else if(df.2013$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2013$pos.fac[i] = "big skill"
    }
    else if(df.2013$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2013$pos.fac[i] = "combo"
    }
}

df.2013$.html <- NA
for(i in 1:nrow(df.2013)){
    df.2013$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2013$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2013$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2013$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2013)){
    print(paste(df.2013$player[i], df.2013$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2013$.html[i])){
        print(i)
        x <- try(scan(df.2013$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2013$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2013$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2013$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2013$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2013$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2013$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2013$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2013$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2013$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2013$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2013$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2013$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2013$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2013$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2013$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2013$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2013$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2013$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2013$pos[i] %in% c("QB")){
            df.2013$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2013$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2013$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2013$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2013$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2013$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2013$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2013$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2013$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2013 <- df.2013 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

draft_2013$rush_att[23] <- 12 ; draft_2013$rush_yds[23] <- 34 ; draft_2013$rush_avg[23] <- 2.9 ; draft_2013$rush_td[23] <- 2
draft_2013$rec[61] <- 60; draft_2013$rec_yds[61] <- 769 ; draft_2013$rec_avg[61] <- 12.8 ; draft_2013$rec_td[61] <- 5
draft_2013$pass_cmp[73] <- 150 ; draft_2013$pass_att[73] <- 295 ; draft_2013$pass_pct[73] <- 50.8 ; draft_2013$pass_yds[73] <- 2053 ; draft_2013$pass_yds_att[73] <- 7.0 ; draft_2013$adj_pass_yds_att[73] <- 6.2 ; draft_2013$pass_td[73] <- 14 ; draft_2013$pass_int[73] <- 11 ; draft_2013$pass_rating[73] <- 117.5 
draft_2013$tackles_solo[101] <- 36 ; draft_2013$tackles_ast[101] <- 42 ; draft_2013$tackles_tot[101] <- 78 ; draft_2013$tackles_loss[101] <- 8 ; draft_2013$sacks[101] <- 4 ; draft_2013$def_int[101] <- 1 ; draft_2013$pass_defended[101] <- 1 ; draft_2013$forced_fumble[101] <- 0
draft_2013$rec[112] <- 26; draft_2013$rec_yds[112] <- 399 ; draft_2013$rec_avg[112] <- 15.3 ; draft_2013$rec_td[112] <- 3
draft_2013$tackles_solo[142] <- 158 ; draft_2013$tackles_ast[142] <- 45 ; draft_2013$tackles_tot[142] <- 203 ; draft_2013$tackles_loss[142] <- 10 ; draft_2013$sacks[142] <- 2 ; draft_2013$def_int[142] <- 7 ; draft_2013$pass_defended[142] <- 0 ; draft_2013$forced_fumble[142] <- 0

#View(draft_2013)

#write.csv(draft_2013, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2013.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2016")
x <- scan("2016 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2016 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2016$pos.fac <- NA 
for( i in seq_along(df.2016$pos)){
    if(df.2016$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2016$pos.fac[i] = "skill"
    }
    else if(df.2016$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2016$pos.fac[i] = "big skill"
    }
    else if(df.2016$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2016$pos.fac[i] = "combo"
    }
}

df.2016$.html <- NA
for(i in 1:nrow(df.2016)){
    df.2016$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2016$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2016$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2016$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2016)){
    print(paste(df.2016$player[i], df.2016$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2016$.html[i])){
        print(i)
        x <- try(scan(df.2016$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2016$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2016$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2016$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2016$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2016$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2016$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2016$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2016$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2016$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2016$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2016$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2016$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2016$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2016$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2016$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2016$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2016$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2016$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2016$pos[i] %in% c("QB")){
            df.2016$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2016$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2016$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2016$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2016$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2016$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2016$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2016$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2016$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2016 <- df.2016 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

draft_2016$tackles_solo[127] <- 83 ; draft_2016$tackles_ast[127] <- 23 ; draft_2016$tackles_tot[127] <- 106 ; draft_2016$tackles_loss[127] <- 7.5 ; draft_2016$sacks[127] <- 1; draft_2016$def_int[127] <- 7 ; draft_2016$pass_defended[127] <- 25 ; draft_2016$forced_fumble[127] <- 4

draft_2016$rush_att[169] <- 600 ; draft_2016$rush_yds[169] <- 3315 ; draft_2016$rush_avg[169] <- 5.5 ; draft_2016$rush_td[169] <- 33 ; draft_2016$rec[169] <- 25 ; draft_2016$rec_yds[169] <- 340 ; draft_2016$rec_avg[169] <- 13.6 ; draft_2016$rec_td[169] <- 3

draft_2016$tackles_solo[244] <- 23 ; draft_2016$tackles_ast[244] <- 13 ; draft_2016$tackles_tot[244] <- 36 ; draft_2016$tackles_loss[244] <- 0 ; draft_2016$sacks[244] <- 0; draft_2016$def_int[244] <- 0 ; draft_2016$pass_defended[244] <- 0 ; draft_2016$forced_fumble[244] <- 0

#View(draft_2016)
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2016")
write.csv(draft_2016, "/Users/draft_2016.csv")
readr::write_csv(draft_2016, "draft_2016.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2015")
x <- scan("2015 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2015 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2015$pos.fac <- NA 
for( i in seq_along(df.2015$pos)){
    if(df.2015$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2015$pos.fac[i] = "skill"
    }
    else if(df.2015$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2015$pos.fac[i] = "big skill"
    }
    else if(df.2015$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2015$pos.fac[i] = "combo"
    }
}

df.2015$.html <- NA
for(i in 1:nrow(df.2015)){
    df.2015$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2015$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2015$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2015$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2015)){
    print(paste(df.2015$player[i], df.2015$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2015$.html[i])){
        print(i)
        x <- try(scan(df.2015$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2015$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2015$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2015$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2015$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2015$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2015$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2015$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2015$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2015$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2015$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2015$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2015$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2015$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2015$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2015$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2015$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2015$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2015$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2015$pos[i] %in% c("QB")){
            df.2015$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2015$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2015$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2015$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2015$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2015$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2015$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2015$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2015$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2015 <- df.2015 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

#View(draft_2015)

#write.csv(draft_2015, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2015.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2014")
x <- scan("2014 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2014 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2014$pos.fac <- NA 
for( i in seq_along(df.2014$pos)){
    if(df.2014$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2014$pos.fac[i] = "skill"
    }
    else if(df.2014$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2014$pos.fac[i] = "big skill"
    }
    else if(df.2014$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2014$pos.fac[i] = "combo"
    }
}

df.2014$.html <- NA
for(i in 1:nrow(df.2014)){
    df.2014$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2014$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2014$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2014$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2014)){
    print(paste(df.2014$player[i], df.2014$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2014$.html[i])){
        print(i)
        x <- try(scan(df.2014$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2014$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2014$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2014$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2014$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2014$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2014$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2014$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2014$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2014$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2014$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2014$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2014$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2014$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2014$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2014$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2014$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2014$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2014$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2014$pos[i] %in% c("QB")){
            df.2014$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2014$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2014$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2014$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2014$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2014$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2014$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2014$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2014$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2014 <- df.2014 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

#View(draft_2014)

#write.csv(draft_2014, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2014.csv")
```

```{r}
setwd("~/Documents/STSCI 4100/Final Project (STSCI 4100)/Datasets/2012")
x <- scan("2012 NFL Combine Results _ Pro-Football-Reference.com.html", what="character", sep="\n")
for(i in length(x)){z <- x[which("<tr data-row" == str_extract(x, "(<tr data-row)", group=1))]}

df <- data.frame(player = rep("", length(z)))
for( i in 1:length(z) ){
    df$player[i] = str_extract( z[i], "(.htm\\\">|\\\"player\\\">)([^<]+)", group=2) # character
    df$pos[i] = str_extract( z[i], "pos\\\">([^<]+)", group=1) # character
    df$school[i] = str_extract( z[i], ">([^<]+)</a></td><td class", group=1) # character
    df$Ht[i] = str_extract( z[i], "height\\\">([^<]+)", group=1) # numeric
    df$Wt[i] = as.numeric(str_extract( z[i], "weight\\\">([^<]+)", group=1)) # numeric
    df$forty_yd[i] = as.numeric(str_extract( z[i], "forty_yd\\\">([^<]+)", group=1)) # numeric
    df$vertical[i] = as.numeric(str_extract( z[i], "vertical\\\">([^<]+)", group=1)) # numeric
    df$bench[i] = as.numeric(str_extract( z[i], "bench_reps\\\">([^<]+)", group=1)) # numeric 
    df$broad_jump[i] = as.numeric(str_extract( z[i], "broad_jump\\\">([^<]+)", group=1)) # numeric
    df$cone[i] = as.numeric(str_extract( z[i], "cone\\\">([^<]+)", group=1)) # numeric
    df$shuttle[i] = as.numeric(str_extract( z[i], "shuttle\\\">([^<]+)", group=1)) # numeric
    df$draft.round[i] = as.numeric((str_extract( z[i], "s / ([^t|r|s|n])", group=1))) # factor
    df$draft.pick[i] = as.numeric(str_extract( z[i], "s / [^/]+/ ([^t|r|s|n]+)", group=1)) # numeric
    df$draft.team[i] = str_extract( z[i], "draft_info\\\" csk=\\\"[^>]+>([^/|<]+)", group=1) # numeric
}

df.2012 <- df %>%
    mutate(rush_att = NA,
    rush_yds = NA,
    rush_avg = NA,
    rush_td = NA,
    rec = NA,
    rec_yds = NA,
    rec_avg = NA,
    rec_td = NA,

    tackles_solo = NA,
    tackles_ast = NA,
    tackles_tot =NA,
    tackles_loss = NA,
    sacks = NA,
    def_int =NA,
    pass_defended = NA,
    forced_fumble = NA,  

    pass_cmp =NA,
    pass_att = NA,
    pass_pct = NA,
    pass_yds = NA,
    pass_yds_att = NA,
    adj_pass_yds_att = NA,
    pass_td = NA,
    pass_int = NA,
    pass_rating = NA)


df.2012$pos.fac <- NA 
for( i in seq_along(df.2012$pos)){
    if(df.2012$pos[i] %in% c("S", "CB", "WR", "DB")){
        df.2012$pos.fac[i] = "skill"
    }
    else if(df.2012$pos[i] %in% c("DT", "DE", "EDGE", "DL")){
        df.2012$pos.fac[i] = "big skill"
    }
    else if(df.2012$pos[i] %in% c("TE", "RB", "LB", "QB", "FB", "OLB", "ILB")){
        df.2012$pos.fac[i] = "combo"
    }
}

df.2012$.html <- NA
for(i in 1:nrow(df.2012)){
    df.2012$.html[i] <- str_extract(z[i], "\\\"college\\\"><a href=\\\"([^>]+)\\\"", group=1)
}


for(i in which(is.na(df.2012$.html))){
    base.1 <- "https://www.sports-reference.com/cfb/players/"
    string <- str_replace_all(df.2012$player[i], "-", " ")
    first <- tolower(
        removePunctuation(
            str_extract(string, "([^ ]+)", group=1)))
    second <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ ([^ ]+)", group=1)))
    third <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ ([^ ]+)", group=1)))
    fourth <- tolower(
        removePunctuation(
            str_extract(string, "[^ ]+ [^ ]+ [^ ]+ ([^ ]+)", group=1)))
    
    if(!is.na(fourth)){
        content <- paste(first, second, third, fourth, sep="-")
    }
    else if(!is.na(third)){
        content <- paste(first, second, third, sep="-")
    }
    else{
        content <- paste(first, second, sep="-")
    }
    if(grepl("jr", content) | grepl("iii", content)){
        content <- str_replace(content, "-jr|-iii", "")
    }
    df.2012$.html[i] <- paste(base.1, content, "-1.html",sep="")        
}


for( i in 1:nrow(df.2012)){
    print(paste(df.2012$player[i], df.2012$.html[i]))
    Sys.sleep( runif( n=1, min = 3, max = 11 ) )
    
    if(!is.na(df.2012$.html[i])){
        print(i)
        x <- try(scan(df.2012$.html[i], what="character", sep="\n", skip=600, nlines=400))
        if(inherits(x, "try-error")){
            next
        }
        z <- x[which("<tfoot><tr class=" == str_extract(x, "(<tfoot><tr class=)", group=1))][1]
        if(df.2012$pos[i] %in% c("WR", "TE", "RB", "FB")){
            df.2012$rush_att[i] = str_extract(z, "rush_att\\\" >([^<]+)", group=1)
            df.2012$rush_yds[i] = str_extract(z, "rush_yds\\\" >([^<]+)", group=1)
            df.2012$rush_avg[i] = str_extract(z, "rush_yds_per_att\\\" >([^<]+)", group=1)
            df.2012$rush_td[i] = str_extract(z, "rush_td\\\" >([^<]+)", group=1)
            df.2012$rec[i] = str_extract(z, "rec\\\" >([^<]+)", group=1)
            df.2012$rec_yds[i] = str_extract(z, "rec_yds\\\" >([^<]+)", group=1)
            df.2012$rec_avg[i] = str_extract(z, "rec_yds_per_rec\\\" >([^<]+)", group=1)
            df.2012$rec_td[i] = str_extract(z, "rec_td\\\" >([^<]+)", group=1)
        }
        
        else if(df.2012$pos[i] %in% c("S", "CB", "DT", "EDGE", "LB", "DE", "DL", "OLB", "ILB", "DB")){
            df.2012$tackles_solo[i] = str_extract(z, "tackles_solo\\\" >([^<]+)", group=1)
            df.2012$tackles_ast[i] = str_extract(z, "tackles_assists\\\" >([^<]+)", group=1)
            df.2012$tackles_tot[i] = str_extract(z, "tackles_total\\\" >([^<]+)", group=1)
            df.2012$tackles_loss[i] = str_extract(z, "tackles_loss\\\" >([^<]+)", group=1)
            df.2012$sacks[i] = str_extract(z, "sacks\\\" >([^<]+)", group=1)
            df.2012$def_int[i] = str_extract(z, "def_int\\\" >([^<]+)", group=1)
            df.2012$pass_defended[i] = str_extract(z, "pass_defended\\\" >([^<]+)", group=1)
            df.2012$forced_fumble[i] = str_extract(z, "fumbles_forced\\\" >([^<]+)", group=1)    
        }
        
        else if(df.2012$pos[i] %in% c("QB")){
            df.2012$pass_cmp[i] = str_extract(z, "pass_cmp\\\" >([^<]+)", group=1)
            df.2012$pass_att[i] = str_extract(z, "pass_att\\\" >([^<]+)", group=1)
            df.2012$pass_pct[i] = str_extract(z, "pass_cmp_pct\\\" >([^<]+)", group=1)
            df.2012$pass_yds[i] = str_extract(z, "pass_yds\\\" >([^<]+)", group=1)
            df.2012$pass_yds_att[i] = str_extract(z, "pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2012$adj_pass_yds_att[i] = str_extract(z, "adj_pass_yds_per_att\\\" >([^<]+)", group=1)
            df.2012$pass_td[i] = str_extract(z, "pass_td\\\" >([^<]+)", group=1)
            df.2012$pass_int[i] = str_extract(z, "pass_int\\\" >([^<]+)", group=1)
            df.2012$pass_rating[i] = str_extract(z, "pass_rating\\\" >([^<]+)", group=1)
        }
    }
}

draft_2012 <- df.2012 %>%
    filter(!(pos) %in% c("P", "K", "LS", "C", "OL", "OG", "OT")) 

#View(draft_2012)

#write.csv(draft_2012, "/Users/nicholaspaschall/Documents/STSCI 4100/draft_2012.csv")
```